### PR TITLE
Nico Create Menu for Frontend Schools

### LINKED ISSUE #38: Frontend Menu Option
There is a menu option for an admin to get to the schools index page where all of the schools are listed

### PR DESCRIPTION
**Pull request by nicoshinozaki**
In this PR, a menu option for an admin to get to the schools index page where all of the schools are listed is created.

Now that the menu option is available, I'm free to work on the 'create' and 'edit' options for the School menu item

Deployed at: https://organic-nicoshinozaki-dev.dokku-10.cs.ucsb.edu

Closes #38

### CODE REVIEW

**Review by SloggyYoggy — DISMISSED** [review]
image

From checking on the deployment and from the code everything looks good to me!

**Review by NevMan1 — DISMISSED** [review]
LGTM

**Review by ukyl — DISMISSED** [review]
lgtm

**Review by pconrad — DISMISSED** [review]
Code looks ok; will need to test on dokku before merging.

**Pull request merged**
